### ISSUE TITLE
Module .../node_modules/angular2-swing/dist/index.js does not export SwingModule

### ISSUE THREAD

**Issue by codisms** [ksachdeva/angular2-swing#10]
Using Ionic 2 RC 0 with Angular 2 final, I get the following error:
```
[05:23:16]  Error: Module .../node_modules/angular2-swing/dist/index.js does not export SwingModule (imported by .../.tmp/app/app.module.js)
    at Module.trace (.../node_modules/rollup/dist/rollup.js:7677:29)
    at ModuleScope.findDeclaration (.../node_modules/rollup/dist/rollup.js:7300:22)
    at Scope.findDeclaration (.../node_modules/rollup/dist/rollup.js:5351:39)
    at Identifier.bind (.../node_modules/rollup/dist/rollup.js:6489:29)
    at .../node_modules/rollup/dist/rollup.js:5151:50
    at ArrayExpression.eachChild (.../node_modules/rollup/dist/rollup.js:5165:19)
    at ArrayExpression.bind (.../node_modules/rollup/dist/rollup.js:5151:7)
    at .../node_modules/rollup/dist/rollup.js:5151:50
    at Node.eachChild (.../node_modules/rollup/dist/rollup.js:5168:5)
    at Node.bind (.../node_modules/rollup/dist/rollup.js:5151:7)
```
Code is simple, in app.module.ts:
```
import { SwingModule } from 'angular2-swing';
```
I get the same when trying to import `SwingCardComponent` and `SwingStackComponent`.

**Comment by pueding** [comment]
+1

**Comment by pueding** [comment]
I found it. This problem is related to 'rollup-plugin-commonjs' which is a new module bundler in Ionic2 rc0. Rollup.js cannot find the unresolvable named exports so you need to set 'namedExports' in rollup setting.

You need to change commonjs setting in ./node_modules/@ionic/app-scripts/config/rollup.config.js
`commonjs()`
=> 
`commonjs({
        namedExports: {
            'node_modules/angular2-swing/dist/index.js': [ 'SwingCardComponent', 'SwingStackComponent', 'SwingModule' ]
        }
    })`

**Comment by codisms** [comment]
Is there a way to set that config without having to edit in `node_modules`?

**Comment by TheMadBug** [comment]
I have made a PR to fix this
https://github.com/ksachdeva/angular2-swing/pull/11/files

If you need it urgently before @ksachdeva has time to review it, grab my fork
https://github.com/TheMadBug/angular2-swing
run
npm install (not sure if this is required)
tsc -d

to get an updated dist that will work with Ionic 2.

**Comment by ksachdeva** [comment]
will fix this after reviewing the pull request from @TheMadBug  in next few hours.

**Comment by cjdreiss** [comment]
@TheMadBug thanks, this helped in dev mode using ionic serve.  Unfortunately more work when building for a device because of AoT compiling.  Here's something that sorta explains it.  https://forum.ionicframework.com/t/unexpected-value-ng2completermodule-imported-by-the-module-appmodule/65922/2

I was trying it myself with a fork, but I'm a little over my head.  My coworker will probably be able to help out though.

**Comment by cjdreiss** [comment]
Me and @markhatchell just submitted Pull request #13 to fix my issue as well.  Thanks @TheMadBug for you initial fix.

**Comment by TheMadBug** [comment]
Thanks @cjdreiss I just did the easy bit. I'll bookmark your PR as I'm sure there are 100 other projects that are going to need a similar change.

**Comment by ksachdeva** [comment]
Fixed by @cjdreiss
