### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by tobiasmuecksch** [ksachdeva/angular2-swing#23]
@ksachdeva :
I this repo dead? Since November 2016 no Issues and Pull-Requests are responded to. If you don't want to maintain it anymore, we can certainly can find someone who would love to take it over. Please just be honest with us.

**Comment by Sparkomatic** [comment]
This repo has been invaluable to me, but I too am waiting for the 4 way swipe functionality to me merged since the end of last year.

**Comment by mashhoodr** [comment]
@ksachdeva is it possible for you to add me as a contributor to this repo?

**Comment by ksachdeva** [comment]
Hi @mashhoodr I am adding you as the contributor. Apologies for the delay .. have been extremely occupied for last 6 months to so and since do not use this project (and related technologies) am having a difficult time to maintain it.

Please make sure to update https://github.com/ksachdeva/angular2-swing-example project as well so that example is up to date as well.

Regards & thanks
Kapil

**Comment by mashhoodr** [comment]
Thanks @ksachdeva! I will update the example as well.

**Comment by ksachdeva** [comment]
Hi @mashhoodr please provide your npm user name as well so that you can publish the updated package to npm. I will add you as the collaborator.

If you do not have an account at https://www.npmjs.com please create one.

Regards
Kapil

**Comment by mashhoodr** [comment]
@ksachdeva my npm username is mashhoodr. Thanks!
